useless_test: ENC[AES256_GCM,data:l8A6Ng==,iv:TJAr6Bg7XJ0vXJr51LjybFUppYUKs0mNVCi8kdQNWBI=,tag:gx8lX1nx9r4QvNNzTjwj2w==,type:str]
credentials:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3hItSt6WC9yphwpmZLOa7vb8brI=,iv:ich4S0Nukh496kpiGEECZKZwlAeVtBr33JYzPjrqQ9U=,tag:mOiGgRdFZ44qgreCE9pdFA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ceFyZ1b6flGt59/hcxe4yAS4eip98sM9CypvSR7M9r3DzztucgganA==,iv:EscOG8UC5jFEm88+IFXwn5B9hmURMMUcUlnCr7K7/qw=,tag:vFZocaLy6TJscUBzVkLiFw==,type:str]
email: ENC[AES256_GCM,data:IDTDGIiqjWEcbIj6jwLEhjFvFTFrGvxz,iv:mjOMhwM6GYuezjn6NMa2JI+qNdRszzjSxsPNZpGZ+HE=,tag:YP1Pz1HCnPPRXxiH9KHIvQ==,type:str]
ip_home: ENC[AES256_GCM,data:CgsxoqI71H0Z91S0mJUuUA==,iv:14aZmALUw/+kiCuD/L6Df1hASS3xf39fUrtImHhRwX0=,tag:gjnAb+qvYVTdY7pq+qDYow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10tqjylqsdrzsqektasajpaelpquckgvarzhh0sn8xjzmpw4huafq35z6cg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOXBPUzJhYkdDbFBSektX
            a1ZrK1dEUElYWGxFQWRmQUsvbmkrL1d5dkhBClNuem5YWnk1dDBOK3EzSVJqS2Zi
            RGRHMVBqZVJ0RWpxNkYyd3QxeWxJZzAKLS0tIDNBZUZCUkxWam5OUjE0UlJIdlB2
            U3NyTXBidlNBTk1tRTdCUDJLT1I0Mk0KyARIfFmevxcApm/dbdDvbCDVP/QPT1Ft
            brWDbxUwx3lFSpfyzeun/OVeVkoQO59AD/VhFb7bfEj1eTAy+cGjyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-09T13:12:16Z"
    mac: ENC[AES256_GCM,data:o23ORhTHDGOoZ91sTVUFZ+Qub9kck46RAd3Qio2LipLH+mBWQ2rfPnB8a6H6l9Pwux8PZIxF5q+EPSeBdSY6FiVa3XWV50GBs+DnUlmH9nILbGDbgstkIDG6tsYo7/PZA4pZk/k1dKNCXBfWJ/uJdUK0rYd1efgF2Gbr4GHncsU=,iv:/OMLCBCX2uGOfPcj1QVqz8Gm92GwTlYYDBXYPC2KptU=,tag:leCJBllnxrwk7duLCTnOsg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
